# Generated by Django 5.1.1 on 2024-11-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
