# Generated by Django 5.1.3 on 2024-11-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='added_by_user',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='capo_info',
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='users_and_their_progresses',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='vimeo_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
