# Generated by Django 5.1.3 on 2024-12-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_chord_audio_url_chord_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
