# Generated by Django 5.1.3 on 2024-12-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_userinfo_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
